# -*- coding: utf-8 -*-
"""Correcto parametros longos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WAudbGnF9AsJKmPMHOG0Yu6kpgcniKsx
"""

# =====================================
# Importação de Bibliotecas Essenciais
# =====================================
import os
import json
import zipfile
import xml.etree.ElementTree as ET
from typing import Dict, List, Optional

# =====================================
# Configuração Inicial e Montagem do Google Drive
# =====================================
try:
    from google.colab import drive
    drive.mount('/content/drive')
    print("✅ Google Drive montado com sucesso.")
except ImportError:
    print("Ambiente não é o Google Colab. A montagem do Drive foi ignorada.")
except Exception as e:
    print(f"⚠️  Aviso ao montar o Drive: {e}")


# =====================================
# Funções de Manipulação de Arquivos .aia
# =====================================
def extrair_arquivo_aia(caminho_aia: str, caminho_extrair: str) -> bool:
    """
    Extrai o conteúdo de um arquivo .aia para um diretório, limpando-o previamente.
    """
    try:
        if os.path.exists(caminho_extrair):
            import shutil
            shutil.rmtree(caminho_extrair)
        os.makedirs(caminho_extrair)

        print(f"\n[ETAPA 1/3] Extraindo o arquivo '{os.path.basename(caminho_aia)}'...")
        with zipfile.ZipFile(caminho_aia, 'r') as arquivo_zip:
            arquivo_zip.extractall(caminho_extrair)
        print("✅ Extração concluída com sucesso!")
        return True
    except FileNotFoundError:
        print(f"❌ Erro: Arquivo .aia não encontrado em {caminho_aia}")
        return False
    except zipfile.BadZipFile:
        print(f"❌ Erro: Arquivo {caminho_aia} não é um arquivo zip válido ou está corrompido.")
        return False
    except Exception as e:
        print(f"❌ Erro ao extrair arquivo .aia: {str(e)}")
        return False

def encontrar_arquivos_bky(caminho_extraido: str) -> List[str]:
    """
    Encontra todos os arquivos de blocos (.bky) dentro do diretório extraído.
    """
    print("\n[ETAPA 2/3] Procurando por arquivos de blocos (.bky)...")
    arquivos_bky = []
    src_path = os.path.join(caminho_extraido, "src")
    if not os.path.exists(src_path):
        print("⚠️  Diretório 'src' não encontrado no projeto.")
        return []

    for root, _, files in os.walk(src_path):
        for file in files:
            if file.endswith(".bky"):
                arquivos_bky.append(os.path.join(root, file))

    if arquivos_bky:
        print(f"✅ Encontrados {len(arquivos_bky)} arquivos de tela.")
    else:
        print("⚠️ Nenhum arquivo .bky foi encontrado.")

    return arquivos_bky


# =====================================
# Funções de Análise e Transformação (XML -> AST -> Relatório)
# =====================================
def parse_blockly_xml_to_ast(xml_string: str) -> Optional[Dict]:
    """
    Converte uma string XML do Blockly para uma estrutura de dicionário Python (AST).
    Esta é a etapa de transformação principal.
    """
    # Namespaces usados pelo App Inventor
    BLOCKLY_NS = "https://developers.google.com/blockly/xml"
    XHTML_NS = "http://www.w3.org/1999/xhtml"

    # Notação de Clark para busca com namespaces
    BN = f"{{{BLOCKLY_NS}}}"
    XN = f"{{{XHTML_NS}}}"

    try:
        root = ET.fromstring(xml_string)

        def extract_block_data(block_element):
            if block_element is None:
                return None

            mutation_element = block_element.find(f"{BN}mutation")
            mutation_data = {}
            if mutation_element is not None:
                mutation_data = {k: v for k, v in mutation_element.attrib.items()}
                # Extrai os nomes dos parâmetros dos elementos <arg>
                mutation_data['args'] = [arg.get('name') for arg in mutation_element.findall(f'{XN}arg')]

            block_data = {
                "type": block_element.get("type"),
                "id": block_element.get("id"),
                "mutation": mutation_data,
                "fields": [{"name": f.get("name"), "text": f.text} for f in block_element.findall(f'{BN}field')],
                "values": [{"name": v.get("name"), "block": extract_block_data(v.find(f'{BN}block'))} for v in block_element.findall(f'{BN}value')],
                "statements": [{"name": s.get("name"), "block": extract_block_data(s.find(f'{BN}block'))} for s in block_element.findall(f'{BN}statement')],
                "next": extract_block_data(block_element.find(f'{BN}next/{BN}block'))
            }
            return block_data

        return {"blocks": [extract_block_data(b) for b in root.findall(f'{BN}block')]}

    except ET.ParseError as e:
        print(f"❌ Erro ao parsear XML: {e}")
        return None

def find_procedures_in_ast(ast: Dict) -> List[Dict]:
    """
    Analisa a AST e retorna uma lista de todos os procedimentos definidos.
    CORRIGIDO: Extrai os parâmetros dos elementos 'field' com nome 'VAR...'.
    """
    all_procedures = []
    if not ast or 'blocks' not in ast:
        return []

    procedure_definitions = [
        b for b in ast.get('blocks', [])
        if b and b.get('type') in ['procedures_defnoreturn', 'procedures_defreturn']
    ]

    for proc in procedure_definitions:
        if not proc: continue

        proc_name = 'ProcedimentoSemNome'
        parameters = []

        # Itera pelos campos para encontrar o nome e os parâmetros
        for field in proc.get('fields', []):
            field_name = field.get('name')
            if field_name == 'NAME':
                proc_name = field.get('text', 'ProcedimentoSemNome')
            elif field_name and field_name.startswith('VAR'):
                # Adiciona o texto do campo (nome do parâmetro) à lista
                if field.get('text'):
                    parameters.append(field.get('text'))

        proc_details = {
            "procedure_name": proc_name,
            "parameter_count": len(parameters),
            "parameters": parameters,
        }
        all_procedures.append(proc_details)

    return all_procedures

def gerar_relatorio_smell(procedures: List[Dict], threshold: int):
    """
    Imprime um relatório focado apenas nos procedimentos com o code smell.
    """
    smelly_procedures = [p for p in procedures if p['parameter_count'] > threshold]

    print("\n" + "=" * 20 + " RELATÓRIO DE CODE SMELL " + "=" * 20)
    print(f"Analisando 'Lista de Parâmetros Longa' (Limite > {threshold} parâmetros)")
    print("-" * 64)

    if not smelly_procedures:
        print(f"🎉 Nenhum procedimento com mais de {threshold} parâmetros foi detectado.")
        return

    print(f"Encontrado(s) {len(smelly_procedures)} procedimento(s) suspeito(s):\n")

    for i, case in enumerate(smelly_procedures, 1):
        print(f"🔴 CASO #{i}: Procedimento '{case['procedure_name']}'")
        print(f"   - Parâmetros Encontrados: {case['parameter_count']} (Limite era {threshold})")
        print(f"   - Nomes dos Parâmetros: {', '.join(case['parameters'])}")
        print(f"   - Diagnóstico: Este procedimento tem uma lista de parâmetros longa, o que pode dificultar o seu uso e manutenção.")
        print(f"   - Sugestão: Considere agrupar parâmetros em uma estrutura de dados (como uma lista ou dicionário) ou dividir o procedimento em funções menores.\n")


# =====================================
# Função Principal de Análise
# =====================================
def analisar_projeto_completo(caminho_aia: str, param_threshold: int):
    """
    Orquestra todo o processo de análise de um arquivo .aia.
    """
    diretorio_extraido = "/content/extracted_aia"

    if not extrair_arquivo_aia(caminho_aia, diretorio_extraido):
        return

    arquivos_bky = encontrar_arquivos_bky(diretorio_extraido)
    if not arquivos_bky:
        return

    print("\n[ETAPA 3/3] Analisando cada tela individualmente...")

    for caminho_bky in arquivos_bky:
        screen_name = os.path.basename(caminho_bky).replace('.bky', '')
        print("\n" + "#" * 70)
        print(f"## Analisando a Tela: {screen_name}")
        print("#" * 70)

        # --- Transformação 1: Ler o XML Bruto ---
        try:
            with open(caminho_bky, 'r', encoding='utf-8') as f:
                xml_content = f.read()
            print("\n---------- 1. XML Original (.bky) ----------")
            print(xml_content[:1000] + "..." if len(xml_content) > 1000 else xml_content)
        except Exception as e:
            print(f"❌ Não foi possível ler o arquivo {caminho_bky}: {e}")
            continue

        # --- Transformação 2: Converter XML para AST (Dicionário Python) ---
        ast = parse_blockly_xml_to_ast(xml_content)
        if not ast:
            print(f"⚠️ Não foi possível gerar a AST para a tela {screen_name}.")
            continue
        print("\n\n---------- 2. Estrutura de Dados (AST) Gerada ----------")
        # Usamos json.dumps para imprimir o dicionário de forma legível
        print(json.dumps(ast, indent=2))

        # --- Transformação 3: Analisar a AST e Gerar Relatório ---
        todos_os_procedimentos = find_procedures_in_ast(ast)
        print("\n\n---------- 3. Análise e Relatório Final ----------")
        if not todos_os_procedimentos:
            print("Nenhum procedimento definido foi encontrado nesta tela.")
        else:
            gerar_relatorio_smell(todos_os_procedimentos, param_threshold)

    print("\n\n================ ANÁLISE COMPLETA CONCLUÍDA ================")


# =====================================
# PONTO DE ENTRADA / EXECUÇÃO
# =====================================
if __name__ == "__main__":
    # <-- MUDE ESTE CAMINHO para o seu arquivo .aia
    caminho_do_arquivo_aia = "/content/drive/MyDrive/Colab Notebooks/smells_appinventor2/projectos_para_analise/ListaPARAMETRO_GERSON_appListaDeTarefas.aia"

    # Um procedimento é considerado "longo" se tiver MAIS do que este número de parâmetros.
    LIMITE_DE_PARAMETROS = 3

    if os.path.exists(caminho_do_arquivo_aia):
        analisar_projeto_completo(caminho_do_arquivo_aia, LIMITE_DE_PARAMETROS)
    else:
        print(f"❌ ERRO CRÍTICO: O arquivo .aia não foi encontrado em '{caminho_do_arquivo_aia}'.")
        print("   Por favor, verifique o caminho e certifique-se de que o arquivo existe no seu Google Drive.")
        print("   Lembre-se de que o caminho diferencia maiúsculas de minúsculas.")